version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "10000:10000"
    env_file: .env
    container_name: fastapi_app
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 10000 --reload"

  postgres:
    image: postgres:latest
    container_name: db_app
    environment:
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASS}  
      POSTGRES_DB: ${DB_NAME}  
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis_app
    ports:
      - "${REDIS_PORT}:6379"

